[meta]
version = 1

[hooks.pre-commit]
fail_fast = true
parallel = true
priority = [
  "verify_formatting",
  "enforce_clippy",
]

[hooks.pre-commit.jobs.verify_formatting]
run = "cargo fmt --check"
fix = "cargo fmt"
stage_fixed = true

[hooks.pre-commit.jobs.enforce_clippy]
run = "cargo clippy -- -D warnings"
