name: "core_api_ci"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    name: "Validate Codebase"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Install Rust Toolchain"
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy, rustfmt"

      - name: "Install Mold Linker"
        uses: rui314/setup-mold@v1

      - name: "Verify Formatting"
        run: cargo fmt --check

      - name: "Enforce Clippy Rules"
        run: cargo clippy -- -D warnings

      - name: "Execute Tests"
        run: cargo test
